version: '3'
services:
  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  mongodb-database:
    image: mongo
    ports:
      - "27017:27017"
